insert into trainingmax (cycleid, movementid, weight) values (1, 1, 220.5);
insert into trainingmax (cycleid, movementid, weight) values (1, 2, 256.5);
insert into trainingmax (cycleid, movementid, weight) values (1, 3, 144);
insert into trainingmax (cycleid, movementid, weight) values (1, 4, 315);
insert into trainingmax (cycleid, movementid, weight) values (2, 1, 225.5);
insert into trainingmax (cycleid, movementid, weight) values (2, 2, 266.5);
insert into trainingmax (cycleid, movementid, weight) values (2, 3, 149);
insert into trainingmax (cycleid, movementid, weight) values (2, 4, 325);
insert into trainingmax (cycleid, movementid, weight) values (3, 1, 230.5);
insert into trainingmax (cycleid, movementid, weight) values (3, 2, 276.5);
insert into trainingmax (cycleid, movementid, weight) values (3, 3, 154);
insert into trainingmax (cycleid, movementid, weight) values (3, 4, 335);
insert into trainingmax (cycleid, movementid, weight) values (4, 1, 235.5);
insert into trainingmax (cycleid, movementid, weight) values (4, 2, 286.5);
insert into trainingmax (cycleid, movementid, weight) values (4, 3, 159);
insert into trainingmax (cycleid, movementid, weight) values (4, 4, 374.5);
insert into trainingmax (cycleid, movementid, weight) values (5, 1, 240.5);
insert into trainingmax (cycleid, movementid, weight) values (5, 2, 296.5);
insert into trainingmax (cycleid, movementid, weight) values (5, 3, 164);
insert into trainingmax (cycleid, movementid, weight) values (5, 4, 374.5);
insert into trainingmax (cycleid, movementid, weight) values (6, 1, 245.5);
insert into trainingmax (cycleid, movementid, weight) values (6, 2, 306.5);
insert into trainingmax (cycleid, movementid, weight) values (6, 3, 169);
insert into trainingmax (cycleid, movementid, weight) values (6, 4, 384.5);
insert into trainingmax (cycleid, movementid, weight) values (7, 1, 250.5);
insert into trainingmax (cycleid, movementid, weight, notes) values (7, 2, 283.5, 'Deloaded by 10% of cycle 6');
insert into trainingmax (cycleid, movementid, weight) values (7, 3, 174);
insert into trainingmax (cycleid, movementid, weight, notes) values (7, 4, 335, 'Deloaded to 335');
insert into trainingmax (cycleid, movementid, weight) values (8, 1, 255.5);
insert into trainingmax (cycleid, movementid, weight) values (8, 2, 293.5);
insert into trainingmax (cycleid, movementid, weight) values (8, 3, 176.5);
insert into trainingmax (cycleid, movementid, weight) values (8, 4, 345);
insert into trainingmax (cycleid, movementid, weight) values (9, 1, 260.5);
insert into trainingmax (cycleid, movementid, weight) values (9, 2, 303.5);
insert into trainingmax (cycleid, movementid, weight, notes) values (9, 3, 158.85, 'Deloaded by 10% of Cycle 8');
insert into trainingmax (cycleid, movementid, weight) values (9, 4, 355);
